### ISSUE TITLE
Just visit the website once before Contributing

### ISSUE THREAD

**Issue by AM1CODES** [AM1CODES/Poke-Dex#109]
Before contributing, i request you to visit the website once to see the pokemons that are already there. There are some unique as well as repeated pokemons currently in the website but i would love to see more new ones.  It's okay if your favourite pokemon is included and you still wish to contribute the same. But if that's not the case then please add new unique ones.

Thank You!

**Comment by Neon-20** [comment]
Hey my #80 didnt got merged..
Please merge it.😀

**Comment by Dheeraj-01** [comment]
Hi, can you assign me I have an Extra Pokémon to this? Thanks :) 😊

**Comment by FireLemons** [comment]
link https://am1codes.github.io/Poke-Dex/
