### ISSUE TITLE
Please Make sure the size of the image matches the other ones

### ISSUE THREAD

**Issue by AM1CODES** [AM1CODES/Poke-Dex#11]
It's a request to the contributors to add images of the same size as others. Disparity in Image size leads to the difference in card shapes and sizes. Keep the images as small as possible so that its easier to accomodate them. You can use the below mentioned website for obtaining the images - https://www.pastemagazine.com/games/pok-mon/the-top-100-pokemon-of-all-time/

Thank you for your cooperation.

**Comment by icodechiranjib** [comment]
I will like to work on it!

**Comment by adityasinghbaghel** [comment]
Hey ! I am interested in this issue. I would like to contribute😊

**Comment by icodechiranjib** [comment]
Check PR #84 Updated index.css [Please Make sure the size of the image matches the other ones #84 
 Updated the CSS of index to make height of all images same irrespective of the upload size

**Comment by AM1CODES** [comment]
> Check PR #84 Updated index.css [Please Make sure the size of the image matches the other ones #84
> Updated the CSS of index to make height of all images same irrespective of the upload size

Sorry brother someone else made a PR changing the card sizes so it's all fixed. Please Make another PR if you wish to adda pokemon. Thank you for your efforts.
