### ISSUE TITLE
Welcome Contributors!

### ISSUE THREAD

**Issue by AM1CODES** [AM1CODES/Poke-Dex#2]
Anyone and everyone is invited to contribute to this mini project. It's a very significant Pull request for anyone who wishes to contribute. Happy Hacking!

**Comment by UshasriMavuri1999** [comment]
Are there any particular requirements to add to this webpage except pokemon cards?

**Comment by AM1CODES** [comment]
No there are no other particular requirements, but if you wish to fix any bugs that you find or you wish to make the any improvements, feel free to do so.

**Comment by UshasriMavuri1999** [comment]
> No there are no other particular requirements, but if you wish to fix any bugs that you find or you wish to make the any improvements, feel free to do so.

Okay then I'll work on it:)

**Comment by rafu01** [comment]
Would definitely love to contribute. Count me in

**Comment by dms-yondy** [comment]
Same, would love to help out :-)

**Comment by al-habibi-1107** [comment]
Would love to add my favourite pokemons in XD

**Comment by kashika3101** [comment]
i would love to contribute to this repo.

**Comment by Juarsh** [comment]
I would also love to conribute to it.

**Comment by bmusuko** [comment]
I would love to add my favorite pokemon too

**Comment by Rit7knight** [comment]
I would also love to add my favorite Pokemon

**Comment by pilgrim-1610** [comment]
would love  to contribute, this  brings back  memories

**Comment by Neon-20** [comment]
Will love to add my favourite pokemons especially .. Pikachu Pika pii

**Comment by jay-deep** [comment]
I will also add my pokemon Brother

**Comment by sandy9808** [comment]
Just a doubt, will all the accepted PR's will be considered for hacktoberfest ?

**Comment by adityasinghbaghel** [comment]
Adding pokemon bro.😊

**Comment by Darknessflowers** [comment]
Going to give this a go later on!

**Comment by climbingryan** [comment]
gonna my favorite pokemon as well

**Comment by AM1CODES** [comment]
> Just a doubt, will all the accepted PR's will be considered for hacktoberfest ?

PRs are considered irrespective of them being merged. If your PR is good, i will surely merge it!

**Comment by saiharsha-22** [comment]
@AM1CODES Hi initially the pic for Snorlax is not getting loaded I have solved that issue and I have added my favorite pokemon which is not there in the Pokedex list.

I have sent a Pull request, can you please check it once.
Added a pokemon and solved a pic loading problem for snorlax #164
![Screenshot (399)](https://user-images.githubusercontent.com/61947484/94840675-6be75580-0436-11eb-809e-830f083d9507.png)

**Comment by nexuspy** [comment]
i would like to contribute

**Comment by SergAgui** [comment]
May I contribute my pokemon as well?

**Comment by AM1CODES** [comment]
> May I contribute my pokemon as well?

Yes Definitely!

**Comment by AM1CODES** [comment]
> @AM1CODES Hi initially the pic for Snorlax is not getting loaded I have solved that issue and I have added my favorite pokemon which is not there in the Pokedex list.
> 
> I have sent a Pull request, can you please check it once.
> Added a pokemon and solved a pic loading problem for snorlax #164
> ![Screenshot (399)](https://user-images.githubusercontent.com/61947484/94840675-6be75580-0436-11eb-809e-830f083d9507.png)

I will have a look at it shortly!

**Comment by mmuhamadamirzaidi** [comment]
Hi. Feels free to contribute to my repository also :D 

[https://github.com/mmuhamadamirzaidi/Hacktoberfest](https://github.com/mmuhamadamirzaidi/Hacktoberfest)

**Comment by gaishhwarya** [comment]
Hi @AM1CODES , I have added 9 pokemons #255 .Have a look!

**Comment by asthakri50** [comment]
Added Vileplume pokemon.

**Comment by khushishikhu** [comment]
@AM1CODES  i have added my pokemon too. please consider that too.

**Comment by hidalgo-vntu** [comment]
May I contribute my pokemon as well?

**Comment by AM1CODES** [comment]
I would like to thank all the contributors for their contributions! Hacktoberfest 2020 was a big learning experience for me and i am glad i could help others out too with this small project. Thank you once again for the contributions and see you at Hacktoberfest 2021.
