### ISSUE TITLE
Add gif instead of photos

### ISSUE THREAD

**Issue by chandankumar1307** [AM1CODES/Poke-Dex#200]
I can add gifs to the website instead of the photos which can make your website more attractive .

**Comment by AM1CODES** [comment]
So you mean replacing all the photos with GIFs? Can you brief me more on the process. I would like to learn more about it.

**Comment by chandankumar1307** [comment]
There are many cool gifs available on the internet. We can use them in your website instead of the plane photos.
only if you like it.
for example this:-
![pikachu](https://media3.giphy.com/media/cRKRsUJ9enVZe/giphy.gif?cid=ecf05e47urjtvyua6j6276sxhdnwim0i3dk7y4223iijyj42&rid=giphy.gif)

**Comment by AM1CODES** [comment]
You can go ahead and try and implement it but i dont think it will be available for all the pokemons. But if you are able to find something that doesnt break the website, go ahead and do it.

**Comment by chandankumar1307** [comment]
Actually, you are right. It's not available for all the pokemon. 
But I hoped that it was available

**Comment by gudianirudha** [comment]
@chandankumar1307 gifs look pretty cool! 
Kindly tell me the website for downloading such cool gifs?

**Comment by gudianirudha** [comment]
@AM1CODES 


![charminder](https://user-images.githubusercontent.com/54411756/95225719-b5121d80-0819-11eb-942c-f48e6f098651.gif)

**Comment by gudianirudha** [comment]
@AM1CODES 
![Uploading tenor.gif…]()

**Comment by AM1CODES** [comment]
@gudianirudha are these available for the pokemons that we have on our website?
If yes please share the website link here.

**Comment by gudianirudha** [comment]
@AM1CODES 
**Link:** https://gifs.alphacoders.com/gifs/by_collection/81
