### ISSUE TITLE
New look to the website

### ISSUE THREAD

**Issue by chandankumar1307** [AM1CODES/Poke-Dex#202]
I have a curious idea for your website...reply to me if you are interested

**Comment by AM1CODES** [comment]
Yes go ahead tell me about it.

**Comment by chandankumar1307** [comment]
I will change the background of your website and do some padding to arrange the headings and it will look something like this.
![image](https://user-images.githubusercontent.com/70543351/94988062-25097500-0588-11eb-83e2-53726788c1c2.png)

**Comment by AM1CODES** [comment]
Go ahead, love it. Once done, just ping me here. I will merge it. Thank you

**Comment by chandankumar1307** [comment]
@AM1CODES Hey :)
I have updated the website and given you a pull request.
You can have a look and if you like it you can merge it.

**Comment by AM1CODES** [comment]
The background looks great but the the position of the text feels a bit odd so if you could adjust that to make it look more centred, it would look great. If the Poke-dex title could be shifted a little lower, it would look much better

**Comment by chandankumar1307** [comment]
For sure I will do it today itself.

**Comment by AM1CODES** [comment]
Also, check the mobile version as well and please fir that too. It got broken after i merged your PR

**Comment by AM1CODES** [comment]
@chandankumar1307 did you fix it?

**Comment by chandankumar1307** [comment]
@AM1CODES I am really sorry but I don't know how to fix it for the mobile version. I haven't studied till there.

**Comment by AM1CODES** [comment]
So just fix the website layout for now, the down arrow button is very low, so just adjust the text and button, i will fix the mobile version. Thank you.

**Comment by chandankumar1307** [comment]
@AM1CODES I have updated the text alignment and sent you a PR.

**Comment by AM1CODES** [comment]
Thank you for that update i checked it, it was perfect. Just one last thing.
![Screenshot (16)](https://user-images.githubusercontent.com/52394145/95158608-a5fb8300-07b9-11eb-823a-a69bb1e27a46.png)

The down arrow seems to be a bit low, can you bring it a little up along with the sentence?

**Comment by chandankumar1307** [comment]
@AM1CODES Sure bro I have done it and sent you a pr.
You can have a look now..everything is fine now.

**Comment by AM1CODES** [comment]
Looks great! Thank you so much for these changes!
