### ISSUE TITLE
Layout Fixes

### ISSUE THREAD

**Issue by AkshatSidharth** [AM1CODES/Poke-Dex#220]
hey,there i have found some layout and alignment bugs. Shall I fix those??

**Comment by AM1CODES** [comment]
can you share a screenshot where you found those bugs?

**Comment by AkshatSidharth** [comment]
I am sharing you the fixed format screenshots
![pic1](https://user-images.githubusercontent.com/62833790/95020700-4c486b00-068a-11eb-81e6-afa4dbce95cf.jpeg)
![pic2](https://user-images.githubusercontent.com/62833790/95020724-6e41ed80-068a-11eb-82da-d15f2cc274e0.jpeg)
![pic3](https://user-images.githubusercontent.com/62833790/95020739-831e8100-068a-11eb-9cbb-aca0ad745833.jpeg)
![pic4](https://user-images.githubusercontent.com/62833790/95020745-92053380-068a-11eb-8b78-783957e954ef.jpeg)

The header section now responds well. If you don't like the changes you may discard.

.
