### ISSUE TITLE
Check for Redundant Entries

### ISSUE THREAD

**Issue by AlenST** [AM1CODES/Poke-Dex#259]
We should also look into making sure there are no redundant entries (i.e., only one instance of each Pokemon should be present in  the Poke Dex

**Comment by AM1CODES** [comment]
Yes initially i permited same entries for one or two people but when this approach became spammy i discontinued it. Right now there are only those pokemons that i allowed, the redundant ones were removed. Thank you.

**Comment by AlenST** [comment]
That's wonderful to hear. :D
But how about automating that process rather than manually going through the entires?
