### ISSUE TITLE
Fixing the Mobile View of the Website[Responsive]

### ISSUE THREAD

**Issue by AM1CODES** [AM1CODES/Poke-Dex#268]
![Screenshot_2020-10-09-08-56-22-687_com android chrome](https://user-images.githubusercontent.com/52394145/95540047-8fe60080-0a0d-11eb-8f59-e788578a530c.jpg)
 The Mobile view of the website is broken, need someone to fix it asap.
Thank you.

**Comment by FireLemons** [comment]
can I have this assigned?

**Comment by AM1CODES** [comment]
> can I have this assigned?

Yes its assigned to you. You can start working on it.

**Comment by AM1CODES** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/52394145/95644442-5b894780-0ad4-11eb-89e3-27af60b2a26e.png)
I think the title just got a little messed up, and the mobile view is also a little out of place. Great job anyway. If possible, please try and fix these. Thank you.

**Comment by AM1CODES** [comment]
Thank you for contributing! The website is responsive now. Just one thing,  the up arrow at the bottom of the page is a little misalligned, so if you can bring it to center again, it would be great and just the like - "Show us your favourite pokemons" could be brought a little bit up in the mobile version so that the down arrow can fit in better. Thank you.

**Comment by FireLemons** [comment]
wait what happened wasn't there a comment about the header text still being misaligned vertically?

**Comment by FireLemons** [comment]
can you send a screenshot of what you just described?

**Comment by FireLemons** [comment]
did you clear the cache? I'm gonna try pulling it up on my laptop to see if anything is different

**Comment by AM1CODES** [comment]
Yes yes that part is cleared, it was an  error on my part. Just the above mentioned issue is remaining rn.

**Comment by AM1CODES** [comment]
![Screenshot_2020-10-10-09-00-58-348_com android chrome](https://user-images.githubusercontent.com/52394145/95644874-62fe2000-0ad7-11eb-93d8-f1ce5a2f84b2.jpg)
![Screenshot_2020-10-10-09-00-51-365_com android chrome](https://user-images.githubusercontent.com/52394145/95644880-74472c80-0ad7-11eb-9361-42123fa23b01.jpg)
i was talking about these two things, if the down button could be shifted a little up.

**Comment by FireLemons** [comment]
ahh I see. I can re create the bug on chrome. It should be fixable

**Comment by FireLemons** [comment]
@AM1CODES could you please mark that merged pull request as `hacktoberfest-accepted` so it counts towards the 4/4 goal?

**Comment by AM1CODES** [comment]
> ahh I see. I can re create the bug on chrome. It should be fixable

Okay. Try and work on it and see what changes you can make to it. Thank you.

**Comment by AM1CODES** [comment]
Yes i will label it as well

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by FireLemons** [comment]
@srishtij2000 I want to share a little thing I noticed when first examining the issue: The width of the header would change after the page finished loading some element which takes several seconds but not longer than a minute.

**Comment by srishtij2000** [comment]
So are you going to assign this issue or should I just submit the PR?

**Comment by FireLemons** [comment]
yeah just submit a pr

**Comment by srishtij2000** [comment]
Okay okay

**Comment by srishtij2000** [comment]
I have issued a PR so kindly review it

**Comment by AM1CODES** [comment]
This issue has been solved. Thank you for contributing @srishtij2000 @FireLemons
