### ISSUE TITLE
Card size

### ISSUE THREAD

**Issue by dms-yondy** [AM1CODES/Poke-Dex#3]
Do you think we should set the card to a fix height? Think it would make the layout a bit cleaner.

**Comment by aniketsingh98571** [comment]
@AM1CODES  @dms-yondy Yes the website is looking weird because of Irrelevant card size. All cards size must be the same.

**Comment by AM1CODES** [comment]
It has been updated. Please take a look at it. Thank You.

**Comment by dms-yondy** [comment]
Looks good!
