### ISSUE TITLE
Suggestion: Remove duplicate Pokemon

### ISSUE THREAD

**Issue by LuigiLegion** [AM1CODES/Poke-Dex#452]
The following are Pokemon that appear more than once in the Pokedex:
- [ ] Pikachu
- [ ] Bulbasaur
- [ ] Squirtle
- [ ] Charizard
- [ ] Arcanine
- [ ] Rayquaza
- [ ] Gyarados
- [ ] Tyrantrum
- [ ] Caterpie
- [ ] Psyduck
- [ ] Eevee
- [ ] Charmander
- [ ] Jolteon
- [ ] Greninja
- [ ] Ho-Oh
- [ ] Oricorio
- [ ] Ninetales
- [ ] Meltan
- [ ] Xerneas
- [ ] Unown
- [ ] Mimikyu
- [ ] Jigglypuff
- [x] Treecko
- [x] Kingler
- [x] Snorlax
- [x] Shuckle
- [x] Electrode
- [x] Dragonair
- [x] Crobat
- [x] Roserade
- [x] Diggersby
- [x] Rampardos
- [x] Chesnaught
- [x] Marowak
- [x] Komala
- [x] Sunflora
- [x] Bastiodon
- [x] Maractus
- [x] Chimecho
- [x] Leavanny
- [x] Wooper
- [x] Tsareena
- [x] Gigalith
- [x] Eiscue
- [x] Swoobat
- [x] Charmeleon
- [x] Metapod
- [x] Chimchar
- [x] Poochyena
- [x] Exeggutor
- [x] Duskull

Some duplicates were created by different users and some were created by the same exact user.
I propose we remove duplicate entries created by the same user.
Please let me know your thoughts, I'm happy to make a PR removing said duplicates.

**Comment by AM1CODES** [comment]
Sure, go ahead and make the PR. Thank you!

**Comment by LuigiLegion** [comment]
Duplicate entries created by the same user have been removed, please check PR #457 .
PR also contains some broken image fixes and name corrections.

The remaining, unchecked Pokemon in this issue have duplicate entries created by different users.

**Comment by AM1CODES** [comment]
Okay. We wont remove duplicate entries from different users. Thank you.
