### ISSUE TITLE
Ability to sort cards

### ISSUE THREAD

**Issue by HARDY8118** [AM1CODES/Poke-Dex#545]
It could be helpful if a button was provided to sort the cads.
Since the pokemon number (#) can be used to identify a pokemon uniquely, maybe a sort button can be added with a dropdown for sorting cards according to their # (number) or name (alphabetically) and maybe default the sort to the order in which the cards were added.
New contributors can add the pokemon number along with the name and for existing ones maybe I can write a simple script which will fetch the pokemon api and add the required details in the existing cards.

**Comment by rehman000** [comment]
Would it be overkill to use something like a relational DB such as sqlite3? @HARDY8118 @AM1CODES

**Comment by rehman000** [comment]
Sqlite3 is not really a full featured RDMS. Like PostgreSQL, or MariaDB. It's just a local unencrypted file that stores all the information for all tables. From my understanding it does not require any back-end server. 

Source: https://www.sqlite.org/serverless.html

My issue is I used it quite frequently for Python and flask. With SQLAlchemy as the ORM. I'm a bit of a novice when it comes to javascript so ofcourse more research would be needed here. I'm not sure what kind of ORM (if any) would apply here. 

We could also store the pokemon info using JSON format. Which honestly sounds less overkill. 

What do you think? @HARDY8118
