### ISSUE TITLE
image extension issues (jpg)

### ISSUE THREAD

**Issue by mihyun-note** [AM1CODES/Poke-Dex#733]
Some images are jpg files, so they are not consistent with other png images.
Changing this file to a png file will make your web page look cleaner!
![캡처](https://user-images.githubusercontent.com/83504363/144378953-d185292a-9451-467d-8b1e-de44fe5efa1a.JPG)
!

**Comment by mihyun-note** [comment]
I changed the link of the jpg image and unified it into a png image.
And I've already made a pull request :)

**Comment by mihyun-note** [comment]
I changed the link of the jpg image and unified it into a png image. (+add vulpix pokemon)
And I've already made a pull request :)

**Comment by AM1CODES** [comment]
Merged.
