### ISSUE TITLE
Description Hover Effect 

### ISSUE THREAD

**Issue by ZeelParekh10** [AM1CODES/Poke-Dex#786]
Hello,
felt nostalgic after seeing this repository as it was one of my favourite shows. I want to add description hover effect without hampering the original card design/ website design as the present one looks uneven. This hover effect will bring evenness to site. I would be happy contributing to this project as am a beginner to open source contributions and hacktoberfest.

Excited to contribute {finger's crossed}

**Comment by AM1CODES** [comment]
Hey @ZeelParekh10 you can work on this

**Comment by ZeelParekh10** [comment]
I have already opened a pull request #788, kindly check it. IT works perfectly and the site is looking good

**Comment by Vaibhavraj-nath-chauhan** [comment]
Can you please assign this issue to me
