### ISSUE TITLE
Please Don't Try to make the website Responsive

### ISSUE THREAD

**Issue by AM1CODES** [AM1CODES/Poke-Dex#9]
I really appreciate your efforts towards making this look better but the bootstrap that i have used helps in making this whole thing Responsive on its own. I suggest you to use the code template i have provided so that its easier for you to contribute as well as makes it easier for me to asses the changes. Once again, i dont wish to stop anyone but by mistake if you make some errors, then the whole website will be affected. Thank you

**Comment by FireLemons** [comment]
Is this issue invalid now because of #268 ?

**Comment by AM1CODES** [comment]
Yes, my  bad. Forgot to close it. Thank you for bringing this to my notice.
